#!/bin/bash
echo "🌐 GaiaScript Web Server Status"
echo "=============================="
echo ""
echo "The GaiaScript application has been compiled and is ready to view!"
echo ""
echo "To start the web server, run:"
echo "  cd docs && python3 -m http.server 8081"
echo ""
echo "Then open your browser to:"
echo "  http://localhost:8081"
echo ""
echo "The demo application includes:"
echo "  • Interactive counter with increment/decrement"
echo "  • Active/Inactive status toggle"
echo "  • Performance metrics display"
echo "  • Mathematical symbol examples"
echo ""
echo "Files created:"
echo "  • docs/index.html - Main HTML page"
echo "  • docs/web/js/demo.js - Working demo application"
echo "  • docs/web/js/gaia-compiled.js - Compiled GaiaScript (needs more work)"
echo ""